### PR TITLE
Fixing weird column issue, couple of additional goodies

### LINKED ISSUE #37: Weird column issue
screen shot 2016-04-27 at 9 27 22 am

### PR DESCRIPTION
**Pull request by leopic**
Sorry I went a little overboard with my changes, but I couldn't pass the opportunity to change a couple of things here and there.

Fixes #37

### CODE REVIEW

File: lib/custom_helpers.rb [hunk 1]
```diff
@@ -5,10 +5,10 @@ def item_to_html(item_hash)
     link = item_hash['link']
     description = item_hash['description']
     <<-EOS
-      <div class="col-md-4">
+      <div class="js-grid-item grid-item">
```
Comment (leopic) [inline lib/custom_helpers.rb]: I recommend using `js-` prefixed classes for anything that's a JS hook.

File: lib/custom_helpers.rb [hunk 2]
```diff
@@ -5,10 +5,10 @@ def item_to_html(item_hash)
...
         <div class="panel panel-default">
           <div class="panel-heading">
-            <a href="#{link}"><h4>#{name}</h4></a>
+            <h4 class="project-title"><a href="#{link}">#{name}</a></h4>
```
Comment (leopic) [inline lib/custom_helpers.rb]: Having a title inside an anchor is perfectly valid HTML5, however, you usually have headers with anchors inside of them so the anchor takes the entire size of the element

File: source/index.html.erb [hunk 3]
```diff
@@ -10,18 +10,19 @@ opener = <<-EOS
...
 
 data.items.sections.map do |section|
   section_name = section['name']
   header = <<-EOS
-      <h2 class="section-header">
-        #{section_name}
-      </h2>
-      <hr />
-    EOS
+    <div class="page-header">
```
Comment (leopic) [inline source/index.html.erb]: The `page-header` class in Bootstrap has the same visual result as having a presentational `hr` tag.

File: source/javascripts/app.js [hunk 4]
```diff
@@ -0,0 +1,7 @@
+$(function() {
```
Comment (leopic) [inline source/javascripts/app.js]: It'd be nice to eventually use RequireJS or something that took care of the modules, but for now, this'll do.

File: source/layouts/layout.erb [hunk 5]
```diff
@@ -14,7 +14,7 @@
     <meta name="description" content="For projects that support RxSwift.">
     <meta name="author" content="RxSwiftCommunity">
 
-    <%= stylesheet_link_tag "bootstrap", "modern-business" %>
+    <%= stylesheet_link_tag "app" %>
```
Comment (leopic) [inline source/layouts/layout.erb]: Consolidated CSS into single file, imports happen in that file.

File: source/layouts/layout.erb [hunk 6]
```diff
@@ -54,7 +54,7 @@
     <!-- /.container -->
 
     <!-- jQuery & Bootstrap -->
-    <%= javascript_include_tag  "jquery", "bootstrap" %>
+    <%= javascript_include_tag  "jquery.min", "bootstrap.min", "masonry.pkgd.min", "app.js" %>
```
Comment (leopic) [inline source/layouts/layout.erb]: Changed bootstrap reference to use the minimized version.

File: source/stylesheets/app.scss [hunk 7]
```diff
@@ -0,0 +1,12 @@
+/* App styles */
```
Comment (leopic) [inline source/stylesheets/app.scss]: This is sort of the `bootstrap` for all styles within the app.

File: source/stylesheets/chrome/_anchors.scss [hunk 8]
```diff
@@ -0,0 +1,10 @@
+// Custom styles for links
```
Comment (leopic) [inline source/stylesheets/chrome/_anchors.scss]: Just because this request was big enough and adding some pizzaz felt right.

File: source/stylesheets/widgets/_masonry.scss [hunk 9]
```diff
@@ -0,0 +1,32 @@
...
+.grid-item {
+  width: 100%;
+
+  .project-title {
+    word-break: break-all;
+  }
+}
+
+// `Tablet` styles
+@media(min-width: 415px) {
```
Comment (leopic) [inline source/stylesheets/widgets/_masonry.scss]: There is for sure a more compass-y like to get this breakpoints to work, but if the page ever becomes a full blown website we'll deal with it then.

**Comment by esttorhe** [comment]
I'm not a webdev and from here it looks good

@leopic any chance to upload a picture of the site rendered with your changes just to double check it looks 👍 ?

I'm 💯 it will look better than now (with the weird columns bug)
but just to double check before merging? 🙈

**Comment by leopic** [comment]
Sure, here's a screenshot for each block

screen shot 2016-04-27 at 6 51 42 pm
screen shot 2016-04-27 at 6 51 32 pm
screen shot 2016-04-27 at 6 51 37 pm
screen shot 2016-04-27 at 6 51 48 pm

**Comment by esttorhe** [comment]
🎉 
i'm pulling the trigger on this @leopic 😬 

Thanks.

Also based on our policy we over push rights whenever someone makes a contribution. 


Interested in joining?

**Comment by leopic** [comment]
Sure, I can't promise any Swift-fu for the time being, but count me in.

**Comment by esttorhe** [comment]
Invitation sent 📬

**Comment by ashfurrow** [comment]
Wow, very cool! Really neat to see how an actual web developer does things, and with excellent comments, too. Thanks a lot!
